package com.google.gwt.angtulargwt.jsr303;

import javax.validation.Validator;
import com.google.gwt.validation.client.GwtValidation;

/* To be generated by Gwt compiler */
@GwtValidation({})
public interface AngularValidator extends Validator {	
}