package com.google.gwt.angtulargwt.jsr303.client;

import javax.validation.Validator;
import com.google.gwt.validation.client.GwtValidation;

/** To be generated by Gwt compiler */
@GwtValidation({})
public interface AngularValidatorImpl extends Validator {	
}